database:
  driverClass: org.postgresql.Driver
  user: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

  # Connection pool settings
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

  # Validation
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  checkConnectionOnBorrow: true

  # Logging
  logValidationErrors: true
  logAbandonedConnections: true

  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.hbm2ddl.auto: validate
    hibernate.show_sql: false
    hibernate.format_sql: true

swaggerBundleConfiguration:
  resourcePackage: com.shadow2y.luthen.service.resource
  title: Luthen API
  version: 1.0.0
  description: API for Luthen application

jwtSecret: 123
jwtExpiryMinutes: 10

# RSA Keys for JWT signing/verification
rsaPrivateKey: ${RSA_PRIVATE_KEY}
rsaPublicKey: ${RSA_PUBLIC_KEY}

# Logging settings
logging:
  level: INFO
  loggers:
    com.shadow2y.luthen: DEBUG
    com.shadow2y.luthen.service.service.LuthenTokenService: DEBUG
    org.hibernate.SQL: ERROR
