database:
  driverClass: org.postgresql.Driver
  user: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

  # Connection pool settings
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

  # Validation
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  checkConnectionOnBorrow: true

  # Logging
  logValidationErrors: true
  logAbandonedConnections: true

  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.hbm2ddl.auto: validate
    hibernate.show_sql: false
    hibernate.format_sql: true

swaggerBundleConfiguration:
  resourcePackage: com.shadow2y.luthen.service.resource
  title: Luthen API
  version: 1.0.0
  description: API for Luthen application

identityConfig:
  smtpHost: smtp.gmail.com
  emailId: ${LUTHEN_EMAIL_ID}
  emailPassword: ${LUTHEN_EMAIL_PASSWORD}
  emailProperties:
    "mail.smtp.auth":
      "true"
    "mail.smtp.starttls.enable":
      "true"
    "mail.smtp.port":
      "587"
  valkeyConfig:
    host: ${IDENTITY_DB_HOST}
    port: ${IDENTITY_DB_PORT}
    password: ${IDENTITY_DB_PASSWORD}
    timeout: 300
    database: 0

authConfig:
  jwtExpiryMinutes: 10
  passwordSaltRounds: 5
  filterAlgorithm: SHA-512
  filterSeed: ${CLIENT_FILTER_SEED}
  filteringWindowMins: 5
  # RSA Keys for JWT signing/verification
  rsaPrivateKey: ${RSA_PRIVATE_KEY}
  rsaPublicKey: ${RSA_PUBLIC_KEY}

clientConfigs:
   MOVITRAK:
      id: ${MOVITRAK_CLIENT_ID}
      secret: ${MOVITRAK_CLIENT_SECRET}
      refreshInMins: 1

# Logging settings
logging:
  level: INFO
  loggers:
    com.shadow2y.luthen: DEBUG
    org.hibernate: ERROR
